spring:
  application:
    name: Server

  profiles:
    active:
      local
    group:
      local-env:
        - local
      dev-env:
        - dev
    include:
      - jwt
      - oauth
      - swagger
