name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ] # dev로 들어오는 PR에서 CI 실행

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 워크플로 실행은 순차 또는 병렬로 동작하는 하나 이상의 job으로 구성됩니다
jobs:
  build:
    name: Build & Test (develop)
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: runmap

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) 앱 빌드(JAR)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build & Test
        run: |
          chmod +x ./gradlew
          # ./gradlew clean build --no-daemon #테스트 포함
          ./gradlew clean bootJar --no-daemon #테스트를 건너뛰고 실행 JAR 만듦

      - name: Upload JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            build/libs/*.jar
